### ISSUE TITLE
bulleted list under a sub-sub-header

### ISSUE THREAD

**Issue by jsta** [Pakillo/rmdTemplates#10]
I am having trouble knitting the ms_pdf template if I include a sub-sub-header (###) with a bulleted list.

A minimum example includes the following block under the `Study Area` subheading:

```
### sub_sub_header1

 * list_item1
```

I am able to knit with either the sub-sub-heading or the bulleted list but not both.

**Comment by Pakillo** [comment]
Thanks @jsta 

I also get an error parsing LaTeX if including your suggested block (i.e. one subheader and **one** list item).

But if including at least two items in the list, it works:

```
### sub_sub_header1

* list_item1

* list_item2
```

Can you please check?

**Comment by jsta** [comment]
Ok, I checked and got the same behavior that you observed. I guess its not a deal-breaker for me because I can't imagine a situation where my finished product has a list of length 1.

**Comment by Pakillo** [comment]
Perfect. Thank you!
