### ISSUE TITLE
ms_pdf abstract update

### ISSUE THREAD

**Issue by Andros-Spica** [Pakillo/rmdTemplates#13]
Hi Paco,
I was trying out the ms_pdf template and it is by far the best solution for academic papers I have found so far. Thank you!
I did have an issue with the abstract by just following the instruction in the template. The abstract place holder was appearing empty even with the default "abstract: no" statement in the yaml hearder. After playing around with the alternatives, I came with this solution, which allows having a keywords variable defined in the header:
in "manuscript.latex" I added this bit about line 181:
```{latex}
\newenvironment{keywords}{
  \textbf{Keywords}:
}
```
and then added this to the yaml header in the Rmd file:
```{latex}
abstract: 'My very long abstract.'
keywords: 'keywordA, keywordB, etc'
```
and erased all other text related to abstract and keyword in the main text.
If you like this solution, I think it would be very useful to have the template updated, especially to people that are not familiar with LaTeX. 
Cheers!

**Comment by Pakillo** [comment]
Hi Andros,

Thanks a lot. I tried to update the latex template but there were a few other things to change to make it compatible with the latest pandoc. So in the end I decided to stick with the pandoc latex template as much as possible, which will be more sustainable in the long term than keeping an independent latex template. 

I think I managed to incorporate all the features the former template had while stressing simplicity (see example here: https://github.com/Pakillo/rmdTemplates/blob/master/inst/examples/ms_PDF_example.pdf). Hope you still like it.

Cheers
