### ISSUE TITLE
ms_pdf bib is very long

### ISSUE THREAD

**Issue by jsta** [Pakillo/rmdTemplates#9]
The file at: inst/rmarkdown/templates/ms_pdf/skeleton/references.bib is very long. Does it make sense to trim this down to a minimum?

**Comment by Pakillo** [comment]
Indeed. Thanks for noting! Just a legacy of previous fiddling with the template.
Fixed now (2d283ca324e7a04e575c1c3db3c494c8799ce7c9).
Thanks again!
